### ISSUE TITLE
Without pull_request_target, percy UI tests are not executed

### ISSUE THREAD

**Issue by MindaugasLaganeckas** [mermaid-js/mermaid-cli#364]
@aloisklink : I would like to use this issue to discuss Percy ui tests problem. By creating the issue, the discussion will stay with the repository project. If you prefer, we can move the discussion to Slack.

The problem: without pull_request_target, pull requests cannot access the secret Percy token and none of the UI tests are executed. This is a problem, because UI tests is a safety net, that helps us to maintain the quality of the tool.
The security issue: as you have pointed in the PR, people may try to do some bad things in the pipeline, if pull_request_target.
Unfortunately, dependabot creates many PRs and bringing every PR to the main repository and double checking with regards to UI tests is not a viable option.

I propose to keep pull_request_target in the pipeline, but in the repository settings I would set under
Fork pull request workflows from outside collaborators
from 'Only first-time contributors will require approval to run workflows.' to 'Require approval for all outside collaborators'.

The review process would be to review the changes first and if OK, approve the workflow runs. What do you think?

**Comment by aloisklink** [comment]
100% agree with the UI tests. Unfortunately, `pull_request_target` won't help, because if you use `pull_request_target`, GitHub actions doesn't checkout the PR branch or merge commit. Instead, it checks out the `target` (aka the `master` branch), where there are no changes.

To illustrate:

```mermaid
%%{init: { 'logLevel': 'debug', 'theme': 'base', 'gitGraph': {'rotateCommitLabel': false}} }%%
gitGraph
    commit id: "1"
    commit id: "2"
    branch my-pr
    branch other-branch
    checkout main
    commit id: "3"
    checkout my-pr
    commit id: "0"
    commit id: "pull_request-HEAD"
    checkout main
    commit id: "pull_request_target"
    merge my-pr tag: "pull_request"
    checkout other-branch
    commit id: "other_commit"
```

`pull_request_target` is before the PR, so it doesn't run the PR code, instead it runs the code from right before the PR.

As an example, if you look at this commit: https://github.com/mermaid-js/mermaid-cli/pull/358/commits/8c484a46424a2500841d55bb4a0d7d7f17b21bf8, you will see that there are two status checks for **Build, test and deploy mermaid-cli Docker image / build**, one for **pull_request_target** and **pull_request**.
 
![image](https://user-images.githubusercontent.com/19716675/186054957-7d6409c5-125e-4649-ba58-c4b114c6649e.png)

If you click on them, you'll see that **pull_request_target**'s `actions/checkout@v3` is actually downloading commit 0e2c06db0dbe36e269bb1fd48ebbd3cc5b05234a (aka the `master` branch).
And **pull_request** is downloading 8c484a46424a2500841d55bb4a0d7d7f17b21bf8 (a temporary merge commit between the PR and the `master` branch.

### What to do since `pull_request_target` won't work

GitHub recommends using `workflow_run`: https://securitylab.github.com/research/github-actions-preventing-pwn-requests/

Basically, we can make a new workflow that is something like:

```yaml
name: Upload to Percy

# read-write repo token
# access to secrets
on:
  workflow_run:
    workflows: ["Build, test and deploy mermaid-cli Docker image"]
    types:
      - completed

jobs:
  upload:
    runs-on: ubuntu-latest
    if: >
      ${{ github.event.workflow_run.event == 'pull_request' &&
      github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: 'Download artifact'
        # this is the artifact created by
        # "Upload diagrams for manual inspection"
        uses: actions/github-script@v3.1.0
        with:
          script: |
            var artifacts = await github.actions.listWorkflowRunArtifacts({
               owner: context.repo.owner,
               repo: context.repo.repo,
               run_id: ${{github.event.workflow_run.id }},
            });
            var matchArtifact = artifacts.data.artifacts.filter((artifact) => {
              return artifact.name == "output"
            })[0];
            var download = await github.actions.downloadArtifact({
               owner: context.repo.owner,
               repo: context.repo.repo,
               artifact_id: matchArtifact.id,
               archive_format: 'zip',
            });
            var fs = require('fs');
            fs.writeFileSync('${{github.workspace}}/mmdc-output.zip', Buffer.from(download.data));
      - run: unzip mmdc-output.zip
      - name: 'Upload to Percy'
        # copied from https://docs.percy.io/docs/github-actions
        # should automatically upload `.png`
        run: npx @percy/cli upload ./
        env:
          PERCY_TOKEN: ${{secrets.PERCY_TOKEN}}
```

I will need to test first if it works, but it looks promising :)
It's secure, and it should run for every PR (including dependabot!)
