### ISSUE TITLE
Configuration file does not exist - Gitlab CI/CD

### ISSUE THREAD

**Issue by 6nv** [mermaid-js/mermaid-cli#441]
**Describe the bug**
I am trying to pull the Docker image in a Gitlab runner to automate generating my necessary charts and uploading them as artifacts for every commit. I found the image `minlag/mermaid-cli` which seems to be the official image; however, when pulling this and running a very simple script, it fails with an error of not finding a configuration file. On a quick search through this code base, I think this is where the error originates from:
```js
const checkConfigFile = file => {
  if (!fs.existsSync(file)) {
    error(`Configuration file "${file}" doesn't exist`)
  }
}
```
Please see my Gitlab CI file and corresponding output for more details. Is there something I am doing wrong on my end?

**To Reproduce**
This is the contents of my `.gitlab-ci.yml` file:
```yml
run:
  stage: build
  image: minlag/mermaid-cli
  script:
    - echo Hello!
```

**Expected behavior**
Pull the Docker image and write "Hello!"

**Obtained Output**
(Where `MY_REPO` is the name/path of my repository.)
```
Running with gitlab-runner 13.3.1 (738bbe5a)
  on docker runner Zf5ntxSi
Preparing the "docker" executor
Using Docker executor with image minlag/mermaid-cli ...
Pulling docker image minlag/mermaid-cli ...
Using docker image sha[2](MY_REPO)56:ecf048befa4dbed77152187b16f95da0e699feaf9eb1c52c8b19ae[3](MY_REPO)96e2da0e6 for minlag/mermaid-cli ...
Preparing environment
00:00
Running on runner-zf[5](MY_REPO)ntxsi-project-123[6](MY_REPO)-concurrent-0 via 28a03886[7](MY_REPO)[8](MY_REPO)5f...
Getting source from Git repository
00:02
Fetching changes with git depth set to 20...
Reinitialized existing Git repository in /builds/ME/MY_REPO/.git/
Checking out 3[9](MY_REPO)69570b as main...
Skipping Git submodules setup
Executing "step_script" stage of the job script
00:01
Configuration file "if [ -x /usr/local/bin/bash ]; then
	exec /usr/local/bin/bash 
elif [ -x /usr/bin/bash ]; then
	exec /usr/bin/bash 
elif [ -x /bin/bash ]; then
	exec /bin/bash 
elif [ -x /usr/local/bin/sh ]; then
	exec /usr/local/bin/sh 
elif [ -x /usr/bin/sh ]; then
	exec /usr/bin/sh 
elif [ -x /bin/sh ]; then
	exec /bin/sh 
elif [ -x /busybox/sh ]; then
	exec /busybox/sh 
else
	echo shell not found
	exit 1
fi
" doesn't exist
ERROR: Job failed: exit code 1
```

Possibly related to #341?

**Comment by aloisklink** [comment]
My gut feeling is that this is because the `minlag/mermaid-cli` sets a custom ENTRYPOINT, which means you can't use normal shell scripting on it.

https://github.com/mermaid-js/mermaid-cli/blob/921f3b11279a06bfec60d9c42ae96a0856afac7a/Dockerfile#L17

See gitlab docs on the `ENTRYPOINT` command: https://docs.gitlab.com/runner/executors/docker.html#the-entrypoint, which recommend creating a new image with that has `"/bin/sh"` as an ENTRYPOINT.

You _might_ be able to work around this by doing something like:

```yaml
run:
  stage: build
  image: minlag/mermaid-cli
  script:
    -  -i src.mmd -o out.pdf
  artifacts:
    paths:
      - out.pdf
```

But I've got no idea if that will work.

Alternatively, installing via NodeJS also works too!

I'm going to close this as **won't fix**, since GitLab uses a Docker image as an environment to execute shell scripts, but the `minlag/mermaid-cli` uses a Docker image as an executable to call `mmdc` directly, so they do have slightly different purposes. But let us know if you disagree, or you think of a way to fix it!

**Comment by Kaligule** [comment]
@6nv In gitlab-ci you can [overwrite the entrypoint](https://docs.gitlab.com/ee/ci/docker/using_docker_images.html#override-the-entrypoint-of-an-image) of the docker image like this: 

```yml
job_name:
  image:
    name: minlag/mermaid-cli:9.3.0
    entrypoint: [""]
```

I guess it does something similar as the `--entrypoint` in `docker run`.

The following job works for me:

```yml
generate_diagrams:
  stage: generate_diagrams
  image:
    name: minlag/mermaid-cli:9.3.0
    entrypoint: [""]
  script:
    - /home/mermaidcli/node_modules/.bin/mmdc -p /puppeteer-config.json --input secret_bank_heist_plan.mmd

  artifacts:
    paths:
      - secret_bank_heist_plan.mmd.svg
    expire_in: 1 day
```
